export const REQUEST_COVID_DATA = 'REQUEST_COVID_DATA';
export const REQUEST_COVID_DATA_SUCCESS = 'REQUEST_COVID_DATA_SUCCESS';
export const ERROR_REQUESTING_COVID_DATA = 'ERROR_REQUESTING_COVID_DATA';
