export const REQUEST_COUNTRY_COVID_DATA = 'REQUEST_COUNTRY_COVID_DATA';
export const REQUEST_COUNTRY_COVID_DATA_SUCCESS = 'REQUEST_COUNTRY_COVID_DATA_SUCCESS';
export const REQUEST_COUNTRY_COVID_DATA_FAILURE = 'REQUEST_COUNTRY_COVID_DATA_FAILURE';
